### ISSUE TITLE
Agenda: new design

### ISSUE THREAD

**Issue by davidwessman** [fsek/voting#119]
- [ ] Use `Agenda`-model only for the main points and ordering.
- [ ] Put all information in a second model, working name `Bullet`
- [ ] Connect `Agenda` to `Bullet`, each `Agenda` must have at least one `Bullet`

### Extras
- [ ] Remove `Documents`-functions and only allow adding them and viewing through `Bullet`

**Comment by davidwessman** [comment]
What do we feel about this?

Create parent/child with different models or something?

**Comment by navro** [comment]
> Create parent/child with different models or something?

Would probably work better than the current solution :)
