### ISSUE TITLE
Searching in tables

### ISSUE THREAD

**Issue by davidwessman** [fsek/voting#203]
Would be useful for:

- [ ] `vote_users#index`

**Comment by navro** [comment]
+1

We would really need this on `vote_users#index`. 5-10% of the users have cards with a broken magnetic stripe, and need to be found manually in the list each time they want to enter/leave.

**Comment by davidwessman** [comment]
Only searching for card number or by name?

**Comment by navro** [comment]
> Only searching for card number or by name?

Searching by name. We already have a feature for searching by card number (and it works fine with the card readers, but it annoying to search manually since almost all users have similar numbers in the beginning)

**Comment by davidwessman** [comment]
Added controller and searching library in #205.
