### ISSUE TITLE
User: set updater with CurrentAttributes instead of Thread

### ISSUE THREAD

**Issue by davidwessman** [fsek/voting#221]
Since 5.1 there exists [CurrentAttributes](http://edgeapi.rubyonrails.org/classes/ActiveSupport/CurrentAttributes.html), seems cool!

Update 04/12:
I was thinking about this for the [User](https://github.com/fsek/voting/blob/master/app/models/user.rb#L92) model.

**Comment by navro** [comment]
>  Using CurrentAttributes instead of our **Thread hack**

Where do we use a thread hack? :)

**Comment by davidwessman** [comment]
@navro
Hm, in the audits I think

**Comment by davidwessman** [comment]
After reading some more I think I misunderstood what we did and what the feature is for.
