### ISSUE TITLE
Login via Wordpress on remote server

### ISSUE THREAD

**Issue by JohanWinther** [fsek/voting#232]
**This is probably very hard to implement correctly and securely.**
We already have a website for our student guild ([ftek.se](https://ftek.se)) where you can create users only with an email matching the school domain. From a user's perspective it would be rather nice to be able to login in this app with the same credentials as the main site, even if the app is hosted on Heroku for example.

I have done some initial testing where I created a user in the rostsystem website for an existing user on the main site. I then changed the password hash in the rostsystem database to the hash in the main site database (Wordpress needs to use bcrypt). From the user's perspective it now looks like they could login with the same information on both sites. But what happens when you change the password on either site?

Ideally it would be nice to have an option to disable password changing on the rostsystem website and only allow logins. This also means no password resets. Now when a user tries to login at rostsystem the application would fetch the hashed password from the main site database and replace that users hashed password. Then it would verify the password normally. New users would only be created on login with a successful hashed password fetch.

There are probably some security aspects which I have overlooked and maybe some rails libraries (Devise?) which makes this hard to implement. Tell me right now if this is impossible to do, because if it is at least possible I think it is worth pursuing for usabilities sake.

**Comment by davidwessman** [comment]
Sounds like a nice feature (we have the same situation, but no demand on school email - so people are signed up with personal emails and now require two sign-ins).

I would however say copying hashed secrets is a very bad practice.

Perhaps looking at some token authorisation via email instead, e.g. [this gem](https://github.com/lynndylanhurley/devise_token_auth), could be a better solution?
