### ISSUE TITLE
Uniqueness in DB

### ISSUE THREAD

**Issue by navro** [fsek/voting#26]
We have some unique validations in the database that do not work well with the paranoia gem. For example, we validate uniqueness for email in the DB. This makes it impossible to delete a user in rails, and then add a new user with the same email, since the DB validation will fail (because of softdelete).

**Comment by davidwessman** [comment]
Hmm, do wee need to allow user deletion? (We do not at fsektionen.se)

**Comment by navro** [comment]
Maybe not. If we really want to, we can use really_destroy! anyway :)

**Comment by davidwessman** [comment]
I think this is a non-issue, as far as I can see. But let keep this here until we get a bit further! 😄

**Comment by navro** [comment]
This is probably not going to be a problem. I'm closing this for now :)
