### ISSUE TITLE
Add number of choices to VotePost

### ISSUE THREAD

**Issue by navro** [fsek/voting#29]
Add the number of choices the user selected to VotePosts.

**Comment by davidwessman** [comment]
But this should only be allowed for VA Kant?

**Comment by davidwessman** [comment]
You mean for counting total amount of votes that should be present at a certain moment?

**Comment by navro** [comment]
Yes

**Comment by navro** [comment]
These values should be compared to the sum of `count` for the VoteOptions

**Comment by davidwessman** [comment]
Should we add a field to each vote which hold blank votes?

I.e. I leave 2 votes when I'm supposed to leave 3, then we add 1 to the `blank`field on the vote?

**Comment by navro** [comment]
I think a field `selected` for the number of selected options would be a little better, since you can not vote if you want all 3 to be blank. You then get:
* Number of votes (total): sum of `selected` for all VPs belonging to a Vote
* Blank votes (total): present users * max options - sum of `selected`

**Comment by davidwessman** [comment]
Just saw your self-assign - and I just implemented this hehe

**Comment by davidwessman** [comment]
Is it okay if `Selected: [0, 2]` is logged? (The number would still be stored in the VotePost)

**Comment by navro** [comment]
It's not really that important, but I would prefer if it was logged on update (that means something strange is going on...) but not on create. I know this means a little more code, but it's better if fewer people have access to this (not so sensitive) information. That means that only those with DB access can find out how many options someone selected. And 2 << 6... :wink:
