### ISSUE TITLE
Newly created users are adjusters by default

### ISSUE THREAD

**Issue by JohanWinther** [fsek/voting#292]
They should become users.

**Comment by davidwessman** [comment]
What do you get if you run `User.new` in `rails console`? :)

**Comment by JohanWinther** [comment]
`#<User id: nil, email: "", firstname: "", lastname: "", created_at: nil, updated_at: nil, deleted_at: nil, presence: false, votecode: nil, card_number: nil, role: "user">`

However this is the dropdown list one the users admin page:
![image](https://user-images.githubusercontent.com/28558941/35862690-cd195c3a-0b4c-11e8-9045-915f70bda616.png)

**Comment by davidwessman** [comment]
Aha! Then I know what the issue is :+1:

**Comment by davidwessman** [comment]
@JohanWinther 
On our app it works fine.
Can you give me the `User.find(@id)` from the console on the user where it fails?

**Comment by JohanWinther** [comment]
`#<User id: 8, email: "redacted@student.chalmers.se", firstname: "redacted", lastname: "redacted", created_at: "2018-02-06 14:22:59", updated_at: "2018-02-06 14:22:59", deleted_at: nil, presence:
 false, votecode: nil, card_number: nil, role: "adjuster">`

This happens to every new user.

**Comment by davidwessman** [comment]
Does this happen locally or on Heroku?

**Comment by JohanWinther** [comment]
Heroku

**Comment by davidwessman** [comment]
Can you give me access to the Heroku app to be able to debug it? 
You can invite me as a collaborator on `david.wesmn@gmail.com`.

**Comment by JohanWinther** [comment]
I've made you a collaborator.

**Comment by davidwessman** [comment]
Cannot recreate and your app works with another database - wierd.
