### ISSUE TITLE
Users can't be adjusted

### ISSUE THREAD

**Issue by JohanWinther** [fsek/voting#296]
When trying to adjust users the following errors emerge (from JS console):
PATCH https://domain.com/admin/narvaro/3 422 (Unprocessable Entity)
and for adjusting out
DELETE https://domain.com/admin/narvaro/3 422 (Unprocessable Entity)

**Comment by davidwessman** [comment]
It will send `422` if there was an issue.

You can e.g. not adjust someone if there is no open agenda or and you cannot adjust out someone if there is an open vote.
Might that be the cause?

**Comment by JohanWinther** [comment]
No open agenda was the problem. You can close the issue!

**Comment by davidwessman** [comment]
But there should probably be a better error message :/
