### ISSUE TITLE
Vote log

### ISSUE THREAD

**Issue by navro** [fsek/voting#4]
#A "vote log" needs to be created. Every time a Vote opens/closes, a VoteUser votes or is marked as present, etc. a record should be created in this log.

Do we need different models for this, or can it be done in a single model?

### Actions to log
- [ ] Vote created
- [ ] Vote updated
- [ ] Vote opened
- [ ] Vote closed

**Comment by davidwessman** [comment]
I would say that we could keep it as one model.
Would be good to list the models in the different cases.

**Comment by davidwessman** [comment]
https://github.com/collectiveidea/audited/tree/4.2-stable
This looks useful

**Comment by navro** [comment]
Implemented in #30
