### ISSUE TITLE
User views

### ISSUE THREAD

**Issue by davidwessman** [fsek/voting#51]
# Start page
- [ ] Current vote
- [x] Current agenda
- [ ] Earlier results?
# Vote page
- [x] If you already voted
- [ ] Some kind of message when the voting closes, atleast some status message.
# Agenda page?

( Will it have its own page or just be embedded at places?)
- [x] Current agenda
- [x] Which agendas are finished
# Header
- [ ] Better navigation to agenda and current vote?
- [ ] Better indication for adjustment

**Comment by davidwessman** [comment]
Should we show closed votes for normal users as well?

**Comment by navro** [comment]
> Should we show closed votes for normal users as well?

You mean in the table? Or that they should have separate pages as well (for displaying results, etc)? Maybe if we have time

**Comment by davidwessman** [comment]
Right now we have a table where we only allow open votes => there can only be one ;) 

Depends on how we show results. But perhaps which vote you have been a part of.

I've started on this.

**Comment by davidwessman** [comment]
I think we should move this issue into first redesigning the Agenda.
