### ISSUE TITLE
Vote: connect to Agenda and publish results

### ISSUE THREAD

**Issue by davidwessman** [fsek/voting#58]
- [x] Connect each Vote to an Agenda, then only allow opening of said vote during said agenda
- [x] When a vote is finished and the results are done, should we allow `publishing` the results?
- [x] Change Vote to have `status` instead of `open`?

**Comment by davidwessman** [comment]
@navro Should we only allow opening a vote connected to an `Agenda`? 
Then we should require `Agenda` to be set.

**Comment by navro** [comment]
> @navro Should we only allow opening a vote connected to an Agenda?
> Then we should require Agenda to be set.

Yes!

**Comment by davidwessman** [comment]
This is done with the `Agenda` update.
