### ISSUE TITLE
Sorting adjustments

### ISSUE THREAD

**Issue by navro** [fsek/voting#59]
In the attendance list, adjustments should be sorted after:

(1) Agenda index
(2) Presence: In, then Out

**Comment by davidwessman** [comment]
You mean they show up in the wrong order? 

Like §1 out, §1 in? Or how should you sort the presence ones? 

Someone could leave and come back during the same agenda, doesn't it have to be sorted by `created_at`?

**Comment by navro** [comment]
They show up in the wrong order if we add or edit adjustments manually

**Comment by davidwessman** [comment]
I think I managed to edit your comment instead of writing a new one here:

> How do we differ between:
> `§3 in, §3 out` with an `§3 out, §3 in`, both can happen?
> 
> We would need to somehow check if they were `present` on `§2`.

**Comment by navro** [comment]
What do you think about adding a column `index` to adjustments, and move up/down buttons to the grid on `vote_users#show`? And automatically setting `Adjustment.maximum('index') + 1` every time a new adjustment is created.

Then the adjustments will be sorted automatically unless the adjuster adds/edits an adjustment manually. And if that happens, the adjuster will also have to sort the list manually...

**Comment by davidwessman** [comment]
Sounds l like a good thing. Nice ajax-training 😄
