### ISSUE TITLE
VoteUser: add mecenat card number or Student ID

### ISSUE THREAD

**Issue by davidwessman** [fsek/voting#60]
For adjusting during the election.
### For users
- [x] Only allow adding `card_number` after confirmation
- [x] Show something on the first page to link to adding card_number
- [x] Adding an image describing which number it is
- [x] Remove the ability to change `card_number`
- [x] Give administrators ability to change users `card_number`
- [x] Add information about which user information is shown to who

**Comment by davidwessman** [comment]
@navro Should we allow updating of Firstname and Lastname?

**Comment by navro** [comment]
> @navro Should we allow updating of Firstname and Lastname?

Only by administrators (adjusters?)
