### ISSUE TITLE
User Terms

### ISSUE THREAD

**Issue by davidwessman** [fsek/voting#78]
Läste på vad man har för skyldigheter om man inte har ett användarvillkor. Nu vill ja ha användarvillkor...
Här är ett förslag jag i princip kopierat från en hyfsat vettig sida. 

Avsnittet om Besökarens ansvar är jag lite tveksam på: t.ex. tillåter vi ju inte så många användare att publicera material eller så. 
Vad tycker du?

### Allmänt om villkoren på webbplatsen
Allmänt om villkoren för användning av innehållet på webbplatsen rostsystem.se.  Dessa användarvillkor är bindande för alla besökare på webbplatsen rostsystem.se.  Genom användandet av webbtjänsten godkänner och accepterar användaren dessa villkor.  Om användaren inte godkänner villkoren ska denne upphöra att använda tjänsten och lämna webbplatsen.  Operatören förbehåller sig rätten att omedelbart stänga webbplatsen för besökaren och/eller göra tjänsterna otillgängliga  för besökaren och/eller på annat sätt förhindra fortsatt otillåtet förfarande i fall då dessa användarvillkor inte efterlevs. Brott mot dessa användarvillkor kan även vara brottsligt förfarande samt medföra skadeståndsskyldighet för besökaren.  Med begreppet "operatören" avses rostsystem.se.

### Personuppgifter
Besökaren är införstådd med och samtycker till att de personuppgifter som besökaren lämnar till operatören kommer att behandlas  av operatören eller annat bolag med vilket operatören samarbetar, i syfte att  
1. fullgöra avtalet med besökaren,
2. fullgöra avtal som besökaren med nyttjande av de tjänster som tillhandahålls av operatören ingår med samarbetspartners till operatören och
3. för statistiska ändamål.

Operatören åtar sig att vid varje tillfälle endast behandla personuppgifter i enlighet med personuppgiftslagen (1998:204). För det fall ett lämnat samtycke återkallas av besökaren, kan webbplatsen och tjänsterna inte användas.

### Besökarens ansvar
Besökaren ansvarar för de åtgärder som besökaren vidtar när besökaren använder webbplatsen och tjänsterna och besökaren åtar sig att hålla operatören skadeslös för krav från tredje man på grund av besökarens användning av webbplatsen och tjänsterna i strid mot användarvillkoren.

### Länkar
Webbplatsen innehåller länkar till andra webbplatser. Sådana webbplatser kontrolleras inte av operatören och operatören är inte ansvarig för innehåll och funktioner hos sådana webbplatser.

### Ansvarsbegränsningar
Alla ansträngningar har gjorts för att säkerställa att innehållet på rostsystem.se är korrekt, men operatören lämnar inga garantier beträffande innehåll, information, tjänster m m som tillhandahålls på eller genom webbplatsen. Operatören lämnar inte heller några garantier beträffande funktion, tillgänglighet, kvalitet, användbarhet eller säkerhet hos tjänsterna eller webbplatsen. Operatören ansvarar inte för direkt eller indirekt förlust eller skada såvida inte operatören handlat grovt vårdslöst eller uppsåtligt. Webbplatsen görs tillgänglig i "befintligt skick".

### Ändringar
Operatören äger rätt att ändra i dessa användarvillkor och besökaren är skyldig att hålla sig uppdaterad om användarvillkoren och läsa igenom användarvillkoren regelbundet. Om besökaren fortsätter att använda webbplatsen och tjänsterna efter det att ändring gjorts av dessa användarvillkor anses besökaren ha accepterat ändringen. Om besökaren vid någon tidpunkt inte accepterar eller kan följa användarvillkoren får besökaren inte använda webbplatsen eller tjänsterna.

**Comment by navro** [comment]
Det ser bra ut, men det där om besökarens ansvar borde vi ta bort!! Känns inte relevant för vår sida :smile

**Comment by davidwessman** [comment]
Okej, jag tog bort delar av det nu.
Ser detta okej ut?
